services:
  telegram_bot:
    build: .
    container_name: telegram_bot_container
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    working_dir: /app
    command: python src/bot.py
