version: '3.8'

services:
  telegram_bot:
    image: telegram_bot:latest
    container_name: telegram_bot_container
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command: python src/bot.py
