name: Run Telegram Bot

on:
  workflow_dispatch:  # Позволяет вручную запускать workflow из интерфейса GitHub
  # schedule:
  #   - cron: "0 */6 * * *"  # (Опционально) автоматически запускать каждые 6 часов

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # или pip install python-telegram-bot python-dotenv и т.п.

      - name: Run bot
        run: |
          # Запускаем бота в фоне
          python main.py &

          # Бесконечный цикл, чтобы workflow не завершался.
          # Каждые 10 минут скрипт делает "ping" (sleep 600), 
          # иначе GitHub может завершить job из-за бездействия.
          while true; do
            echo "Bot is running..."
            sleep 600
          done